[build]
builder = "NIXPACKS"
buildCommand = "cd backend && yarn install && mkdir -p .medusa/server && cp tsconfig.json .medusa/server/ && yarn build"

[deploy]
startCommand = "cd backend && yarn start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3 